// geosamples-ingest-ui-react/src/main/frontend/src/pages/controlled-vocabulary/device/DeviceList.tsx
import InteractiveTable from "../../../components/table/InteractiveTable.tsx";


function DeviceList() {
  return <>
    <InteractiveTable
        breadcrumbs={[
          {
            "active": false,
            "breadcrumbLink": "/",
            "breadcrumbTitle": "Geosamples Ingest Home"
          },
          {
            "active": true,
            "breadcrumbLink": "/device/list",
            "breadcrumbTitle": "Sampling Device"
          }
        ]}
        fields={[
          {
            "label": "Sampling Device"
          },
          {
            "label": "Sampling Device Code"
          }
        ]}
        createText={"Sampling Device"}></InteractiveTable>
  </>
}

export default DeviceList;

// geosamples-ingest-ui/src/main/frontend/src/views/view/main/device/list/DeviceList.vue
<template>
  <InteractiveTable
    :breadcrumbs="[
      { text: 'Geosamples Ingest', to: { name: 'Home' } },
      { text: 'Sampling Device', active: true },
    ]"
    module="device"
    read-authority="ROLE_DEVICE_READ"
    :fields="[
      { label: 'Sampling Device', value: params.device, set: setDevice },
      { label: 'Sampling Device Code', value: params.deviceCode, set: setDeviceCode },
    ]"
    :table-fields="tableFields"
    create-route="DeviceAdd"
    create-text="Add New Sampling Device"
    create-authority="ROLE_DEVICE_CREATE"
    edit-field="device"
    edit-parameter="device"
    edit-route="DeviceEdit"
    edit-authority="ROLE_DEVICE_UPDATE"
  />
</template>

<script>

import {
  mapMutations, mapState,
} from 'vuex';
import InteractiveTable from '@/components/InteractiveTable.vue';

export default {
  components: {
    InteractiveTable,
  },

  methods: {
    ...mapMutations('device', ['setDevice', 'setDeviceCode']),
  },

  computed: {
    ...mapState('device', ['params']),
  },

  data() {
    return {
      deviceId: null,
      deviceCodeId: null,

      tableFields: [
        {
          key: 'device',
          label: 'Sampling Device',
          sortable: true,
        },
        {
          key: 'deviceCode',
          label: 'Sampling Device Code',
          sortable: true,
        },
      ],
    };
  },
};
</script>
